network:
  host: 127.0.0.1
  port_range:
    - 49152
    - 50000
  timeout: 0.02
  last_successful_port: null
routing:
  playback_only:
    - <client_command type="assign_source" output="line_output_1" source="daw_output_1"/>
    - <client_command type="assign_source" output="line_output_2" source="daw_output_2"/>
  standalone:
    - <client_command type="assign_source" output="line_output_1" source="analogue_input_1"/>
    - <client_command type="assign_source" output="line_output_2" source="analogue_input_2"/>
    - <client_command type="flash_hardware"/>
